default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  url: postgres://postgres:postgres@localhost

development:
  <<: *default
  database: handcuffs_development

test:
  <<: *default
  database: handcuffs_test
