name: Test Handcuffs

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

defaults: &defaults
  runs-on: ubuntu-latest
  env:
    POSTGRES_DB_USERNAME: postgres
    POSTGRES_DB_PASSWORD: postgres
    POSTGRES_DB: handcuffs_test
    RAILS_ENV: test
    BUNDLER_VERSION: 1.17.3

jobs:
  run_tests:
    name: Run Tests
    strategy:
      matrix:
        ruby: ['2.3', '2.4', '2.5', '2.6', '2.7']
    defaults: *defaults
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.144.2
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install Bundler
        run: gem install bundler:1.17.3

      - name: Install Ruby Dependencies
        run: |
          bundle install
          cd spec/dummy
          bundle install

      - name: Install Appraisals Dependencies
        run: bundle exec appraisal install

      - name: Setup Database
        run: |
          cd spec/dummy
          bundle exec rake db:create db:migrate --trace

      - name: Run Appraisals Tests
        run: bundle exec appraisal rspec

      - name: Run Dummy App Tests
        run: cd spec/dummy && bin/rspec
