name: Test Handcuffs

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1']
    env:
      POSTGRES_DB: handcuffs_test
      POSTGRES_DB_HOST: 127.0.0.1
      POSTGRES_DB_USERNAME: postgres
      POSTGRES_DB_PASSWORD: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
      RAILS_ENV: test
      BUNDLER_VERSION: 2.4.19
    services:
      postgres:
        image: postgres:14.6
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: handcuffs_test1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.154.0
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install Bundler
        run: gem install bundler:2.4.19

      - name: Install Ruby Dependencies
        run: |
          psql -h 127.0.0.1 -U postgres -c "CREATE DATABASE handcuffs_test;"
          bundle install
          cd spec/dummy
          bundle install

      - name: Install Appraisals Dependencies
        run: bundle exec appraisal install

      - name: Setup Database
        run: |
          cd spec/dummy
          bundle exec rake db:migrate --trace

      - name: Run Appraisals Tests
        run: bundle exec appraisal rspec

      - name: Run Dummy App Tests
        run: cd spec/dummy && bin/rspec
